[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
yaycazz = "57naiGrCabhS1B2jkZudgtfK356Ygx9BqFyxYNGVKu6Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/berkay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
